#!/bin/bash -i
: '
/*-------------------------------------
install
nft
    by Daniel Richards (ddrichar@ucsc.edu)
       on 4-8-2018
--------------------------------------*/
'
echo "Entering configuraton..."
printf "Name : "
read NAME 
printf "email address [or github URL] : "
read EMAIL 
MY_EMAIL="ddrichar@ucsc.edu"
MY_NAME="Daniel Richards"

cd templates
grep -rli "$MY_EMAIL" * | xargs -I? sed -i '' "s/$MY_EMAIL/$EMAIL/g" ?
grep -rli "$MY_NAME" * | xargs -I? sed -i '' "s/$MY_NAME/$NAME/g" ?
cd ..

NFT_PATH=`pwd`/new_from_template.py
ALIAS="alias nft='$NFT_PATH'"
echo $ALIAS >> ~/.bash_profile
cd ~
HOME=`pwd`
source $HOME/.bash_profile
login
